scribe:
  auth:
    login-url: https://scribe-hub-production.us.auth0.com
    #login-url: https://scribe-hub-staging.us.auth0.com
    grant-type: client_credentials
    enable: true
    audience: api.production.scribesecurity.com
    #audience: api.staging.scribesecurity.com
  url: https://airflow.scribesecurity.com
  #url: https://airflow.staging.scribesecurity.com
  enable: true
attest:
    cocosign:
        signer:
            x509:
                enable: true
                private: env://SIGNER_KEY
                cert: env://SIGNER_CERT
                ca: env://COMPANY_CA
        verifier:
            x509:
                enable: true
                cert: env://SIGNER_CERT
                ca: env://COMPANY_CA
    
